### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION julia-0.5

### ISSUE THREAD

**Issue by mmoh** [JuliaLang/WinRPM.jl#53] opened 2015-10-15 20:25 UTC
```julia
julia> Pkg.checkout("WinRPM")
INFO: Checking out WinRPM master...
INFO: Pulling WinRPM latest master...
INFO: No packages to install, update or remove

julia> using WinRPM

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x64f12736 -- jl_init_types at C:\Julia\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)
jl_init_types at C:\Julia\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)
jl_apply_generic at C:\Julia\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)
xp_make_parser at error.jl:21
xp_parse at C:\Users\Mustafa\.julia\v0.5\LibExpat\src\LibExpat.jl:92
jl_apply_generic at C:\Julia\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)
update at C:\Users\Mustafa\.julia\v0.5\WinRPM\src\WinRPM.jl:163
__init__ at C:\Users\Mustafa\.julia\v0.5\WinRPM\src\WinRPM.jl:41
jlcall___init___3122 at  (unknown line)
jl_apply_generic at C:\Julia\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)
jl_module_run_initializer at C:\Julia\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)
jl_eval_module_expr at C:\Julia\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at C:\Julia\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)
jl_parse_eval_all at C:\Julia\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)
jl_load_ at C:\Julia\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)
include at boot.jl:261
jl_apply_generic at C:\Julia\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)
include_from_node1 at loading.jl:382
jl_apply_generic at C:\Julia\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_expr at C:\Julia\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_thunk_with at C:\Julia\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at C:\Julia\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)
jl_f_tuple at C:\Julia\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)
require at sysimg.jl:14
jlcall_require_2773 at  (unknown line)
jl_apply_generic at C:\Julia\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)
jl_init_serializer at C:\Julia\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at C:\Julia\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)
jl_f_tuple at C:\Julia\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)
eval_user_input at REPL.jl:3
jlcall_eval_user_input_1575 at  (unknown line)
jl_apply_generic at C:\Julia\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)
anonymous at REPL.jl:92
jl_switchto at C:\Julia\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)

julia> versioninfo()
Julia Version 0.5.0-dev+757
Commit 8adbf7a (2015-10-13 20:10 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by tkelman** [comment] 2015-10-15 20:28
I'm pretty sure this was caused by https://github.com/JuliaLang/julia/pull/13506

**Comment by tkelman** [comment] 2015-10-20 14:38
What's your `Pkg.status()` ?

**Comment by mmoh** [comment] 2015-10-20 14:40
checkout out master 
```julia
julia> Pkg.checkout("WinRPM")
INFO: Checking out WinRPM master...
INFO: Pulling WinRPM latest master...
INFO: No packages to install, update or remove

julia> using WinRPM
INFO: Recompiling stale cache file C:\Users\Mustafa\.julia\lib\v0.5\Compat.ji for module Compat.
INFO: Recompiling stale cache file C:\Users\Mustafa\.julia\lib\v0.5\Zlib.ji for module Zlib.
INFO: Recompiling stale cache file C:\Users\Mustafa\.julia\lib\v0.5\URIParser.ji for module URIParser.
INFO: Recompiling stale cache file C:\Users\Mustafa\.julia\lib\v0.5\BinDeps.ji for module BinDeps.
INFO: Recompiling stale cache file C:\Users\Mustafa\.julia\lib\v0.5\SHA.ji for module SHA.
WARNING: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download
WARNING: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download

julia> WinRPM.update()
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/ee15ea15cad23ee9fb29016b9ff177657ee3571e966b2ee75cff3cc71b911671-primary.xml.gz
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/19ff36116cb4069991c2f58621c93dda1c6b13fb6c734a2e5d197f33bee0020a-primary.xml.gz

julia> Pkg.status()
39 required packages:
 - Atom                          0.1.1+             master
 - Blink                         0.1.5              master
 - CUDA                          0.1.0
 - Cairo                         0.2.31
 - Clp                           0.1.1
 - CodeTools                     0.1.0+             master
 - Devectorize                   0.4.2
 - DistributedArrays             0.1.6
 - GLPlot                        0.0.5+             master
 - Gadfly                        0.3.17+            master
 - Graphs                        0.5.6
 - Gtk                           0.9.2
 - HTTPClient                    0.1.6
 - HttpServer                    0.1.4
 - IJulia                        1.1.7
 - IProfile                      0.3.1+             master
 - ImageView                     0.1.17
 - Images                        0.4.50
 - Immerse                       0.0.8
 - Interact                      0.2.1
 - JuMP                          0.10.2
 - MATLAB                        0.2.4
 - MPI                           0.3.2
 - Mosek                         0.2.0
 - ProfileView                   0.1.1
 - ProgressMeter                 0.2.1
 - PyPlot                        2.1.1
 - QuantEcon                     0.2.1
 - RDatasets                     0.1.2
 - Reactive                      0.2.4
 - SFML                          0.1.0
 - StatsBase                     0.7.4
 - SymPy                         0.2.30
 - TestImages                    0.0.8
 - Tk                            0.3.6
 - ValidatedNumerics             0.1.3
 - WinRPM                        0.1.12+            master
 - Yeppp                         0.0.8
 - ZMQ                           0.3.0
```

Looks to be working now

**Comment by tkelman** [comment] 2015-10-20 14:51
Thanks. That's very strange, are you using the same build of Julia as you were a few days ago?

**Comment by mmoh** [comment] 2015-10-20 14:52
No I just downloaded the nightly build, just now before sending the last message.

Sent from my Windows Phone
________________________________

**Comment by tkelman** [comment] 2015-10-20 15:02
I see, thanks. Ref https://github.com/JuliaLang/julia/pull/13506#issuecomment-149591986 - this may have been fixed (and/or caused?) by some other change on master of julia. According to some appveyor logs we see the failure at https://github.com/JuliaLang/julia/commit/03f28fdc9c2290d44d132b32b5dabe3b7ea0350a but not at https://github.com/JuliaLang/julia/commit/8a862705f2d058f17d5757702f43b6c685091b0f. Would be worth trying to pinpoint that further, let me see if there are nightlies anywhere within that range.

**Comment by tkelman** [comment] 2015-10-20 15:05
Would you be willing to test the following for me, since you were getting this to happen on your system before?

https://s3.amazonaws.com/julianightlies/bin/winnt/x64/0.5/julia-0.5.0-d35e69c755-win64.exe
https://s3.amazonaws.com/julianightlies/bin/winnt/x64/0.5/julia-0.5.0-d711b7d8a1-win64.exe
https://s3.amazonaws.com/julianightlies/bin/winnt/x64/0.5/julia-0.5.0-d9f7c21258-win64.exe
https://s3.amazonaws.com/julianightlies/bin/winnt/x64/0.5/julia-0.5.0-9eee388f63-win64.exe

Much appreciated, if you can. Thanks!

**Comment by tkelman** [comment] 2015-10-20 15:14
If you're too busy, I can wait to see what appveyor says in https://ci.appveyor.com/project/tkelman/lightxml-jl/build/1.0.124, so it's not that big a deal.

**Comment by mmoh** [comment] 2015-10-20 15:26
julia-0.5.0-d9f7c21258 works
julia-0.5.0-d711b7d8a1 works
julia-0.5.0-d35e69c755   works
julia-0.5.0-9eee388f63    fails
with error msg
```
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x64f12736 -- jl_init_types at C:\Users\Mustafa\Desktop\julia-0.5.0-9eee388f63\bin\libjulia.dll (unknown line)
jl_init_types at C:\Users\Mustafa\Desktop\julia-0.5.0-9eee388f63\bin\libjulia.dll (unknown line)
jl_apply_generic at C:\Users\Mustafa\Desktop\julia-0.5.0-9eee388f63\bin\libjulia.dll (unknown line)
xp_make_parser at error.jl:21
xp_parse at C:\Users\Mustafa\.julia\v0.5\LibExpat\src\LibExpat.jl:92
jl_apply_generic at C:\Users\Mustafa\Desktop\julia-0.5.0-9eee388f63\bin\libjulia.dll (unknown line)
update at C:\Users\Mustafa\.julia\v0.5\WinRPM\src\WinRPM.jl:153
__init__ at C:\Users\Mustafa\.julia\v0.5\WinRPM\src\WinRPM.jl:41
jlcall___init___2271 at  (unknown line)
jl_apply_generic at C:\Users\Mustafa\Desktop\julia-0.5.0-9eee388f63\bin\libjulia.dll (unknown line)
jl_module_run_initializer at C:\Users\Mustafa\Desktop\julia-0.5.0-9eee388f63\bin\libjulia.dll (unknown line)
jl_eval_module_expr at C:\Users\Mustafa\Desktop\julia-0.5.0-9eee388f63\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at C:\Users\Mustafa\Desktop\julia-0.5.0-9eee388f63\bin\libjulia.dll (unknown line)
jl_parse_eval_all at C:\Users\Mustafa\Desktop\julia-0.5.0-9eee388f63\bin\libjulia.dll (unknown line)
jl_load_ at C:\Users\Mustafa\Desktop\julia-0.5.0-9eee388f63\bin\libjulia.dll (unknown line)
include at boot.jl:261
jl_apply_generic at C:\Users\Mustafa\Desktop\julia-0.5.0-9eee388f63\bin\libjulia.dll (unknown line)
include_from_node1 at loading.jl:382
jl_apply_generic at C:\Users\Mustafa\Desktop\julia-0.5.0-9eee388f63\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_expr at C:\Users\Mustafa\Desktop\julia-0.5.0-9eee388f63\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_thunk_with at C:\Users\Mustafa\Desktop\julia-0.5.0-9eee388f63\bin\libjulia.dll (unknown line)

jl_eval_with_compiler_p at C:\Users\Mustafa\Desktop\julia-0.5.0-9eee388f63\bin\libjulia.dll (unknown line)
jl_f_tuple at C:\Users\Mustafa\Desktop\julia-0.5.0-9eee388f63\bin\libjulia.dll (unknown line)
require at sysimg.jl:14
jlcall_require_1572 at  (unknown line)
jl_apply_generic at C:\Users\Mustafa\Desktop\julia-0.5.0-9eee388f63\bin\libjulia.dll (unknown line)
jl_init_serializer at C:\Users\Mustafa\Desktop\julia-0.5.0-9eee388f63\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at C:\Users\Mustafa\Desktop\julia-0.5.0-9eee388f63\bin\libjulia.dll (unknown line)
jl_f_tuple at C:\Users\Mustafa\Desktop\julia-0.5.0-9eee388f63\bin\libjulia.dll (unknown line)
eval_user_input at REPL.jl:3
jlcall_eval_user_input_1570 at  (unknown line)
jl_apply_generic at C:\Users\Mustafa\Desktop\julia-0.5.0-9eee388f63\bin\libjulia.dll (unknown line)
anonymous at REPL.jl:92
jl_switchto at C:\Users\Mustafa\Desktop\julia-0.5.0-9eee388f63\bin\libjulia.dll (unknown line)
```

**Comment by tkelman** [comment] 2015-10-20 15:49
Great, thanks, so https://github.com/JuliaLang/julia/pull/13553 apparently fixed this, and I guessed wrong at the cause. I'll close this then, but please do keep an eye out! Helps to have people willing to test things out on the bleeding edge and flagging early if there are problems.

**Closed by tkelman** 2015-10-20 15:49 UTC

**Comment by mmoh** [comment] 2015-10-20 20:09
Glad to help!
